insert into EXCHANGE(FROM_CURRENCY, TO_CURRENCY, CONVERSION_MULTIPLE, PORT) values ('USD', 'INR', 65, 0);
insert into EXCHANGE(FROM_CURRENCY, TO_CURRENCY, CONVERSION_MULTIPLE, PORT) values ('JPY', 'INR', 50, 0);
insert into EXCHANGE(FROM_CURRENCY, TO_CURRENCY, CONVERSION_MULTIPLE, PORT) values ('EUR', 'INR', 120, 0);